
GET http://localhost:4000/products

###
GET http://localhost:4000/products
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "name":"product 1",
    "description":"best product",
    "price":100,
    "discount": 10

}

###
PUT http://localhost:4000/products
Content-Type: application/json

{
    "title":"updated product",
    "description":"updated product",
    "price":102,
    "discount": 20
}

###

DELETE http://localhost:4000/products

